version: "3"
services:
  app:
    container_name: "app"
    build:
     context: ./
     dockerfile: ./Dockerfile
    environment:
      THRIFT_ENDPOINT: http://jaeger:14268/api/traces
      CONSUMER_GROUP: jaeger-test
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: jaeger_tracing
    volumes:
     # - ~/.air:/src/go
     - ./:/src/go
     - $GOPATH/pkg/mod:/go/pkg/mod
    ports:
     - 8080:8080
    working_dir: /src/go
    command: ./air -c air.conf
    depends_on:
      - kafka
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.11
    ports:
      - 127.0.0.1:5775:5775/udp # accept zipkin.thrift over compact thrift protocol
      - 127.0.0.1:6831:6831/udp # accept jaeger.thrift over compact thrift protocol
      - 127.0.0.1:6832:6832/udp # accept jaeger.thrift over binary thrift protocol
      - 127.0.0.1:5778:5778 # serve configs
      - 127.0.0.1:9411:9411 # zipkin Optional
      - 127.0.0.1:16686:16686 # serve frontend
      - 127.0.0.1:14268:14268 # accept jaeger.thrift directly from clients

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: none

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "jaeger_tracing:1:1"
    depends_on:
      - zookeeper
    logging:
      driver: none